// Code generated by sqlabble, DO NOT EDIT.
package baz

import (
	"database/sql"
	"strings"

	"github.com/sqlabble/sqlabble"
	"github.com/sqlabble/sqlabble/stmt"
)

// ArticleDB Article table
type ArticleDB struct {
	Table                stmt.Table
	TableAlias           stmt.TableAlias
	ArticleIDColumn      stmt.Column
	ArticleIDColumnAlias stmt.ColumnAlias
	SubjectColumn        stmt.Column
	SubjectColumnAlias   stmt.ColumnAlias
	BodyColumn           stmt.Column
	BodyColumnAlias      stmt.ColumnAlias
}

// NewArticleDB Create a/an ArticleDB
func NewArticleDB(aliases ...string) ArticleDB {
	alias := strings.Join(aliases, ".")
	if alias == "" {
		alias = "articles"
	}
	return ArticleDB{
		Table:                stmt.NewTable("articles"),
		TableAlias:           stmt.NewTable("articles").As(alias),
		ArticleIDColumn:      stmt.NewTableAlias(alias).Column("article_id"),
		ArticleIDColumnAlias: stmt.NewTableAlias(alias).Column("article_id").As(strings.Join(append(aliases, "ArticleID"), ".")),
		SubjectColumn:        stmt.NewTableAlias(alias).Column("subject"),
		SubjectColumnAlias:   stmt.NewTableAlias(alias).Column("subject").As(strings.Join(append(aliases, "Subject"), ".")),
		BodyColumn:           stmt.NewTableAlias(alias).Column("body"),
		BodyColumnAlias:      stmt.NewTableAlias(alias).Column("body").As(strings.Join(append(aliases, "Body"), ".")),
	}
}

// Register -
func (a ArticleDB) Register(mapper map[string]interface{}, dist *Article, aliases ...string) {
	mapper[strings.Join(append(aliases, "ArticleID"), ".")] = &dist.ArticleID
	mapper[strings.Join(append(aliases, "Subject"), ".")] = &dist.Subject
	mapper[strings.Join(append(aliases, "Body"), ".")] = &dist.Body
}

// Columns -
func (a ArticleDB) Columns() []stmt.Column {
	return []stmt.Column{
		a.ArticleIDColumn,
		a.SubjectColumn,
		a.BodyColumn,
	}
}

// ColumnAliases -
func (a ArticleDB) ColumnAliases() []stmt.ColumnAlias {
	aliases := []stmt.ColumnAlias{
		a.ArticleIDColumnAlias,
		a.SubjectColumnAlias,
		a.BodyColumnAlias,
	}
	return aliases
}

// Selectors -
func (a ArticleDB) Selectors() []stmt.ValOrColOrAliasOrFuncOrSubOrFormula {
	as := a.ColumnAliases()
	is := make([]stmt.ValOrColOrAliasOrFuncOrSubOrFormula, len(as))
	for i, a := range as {
		is[i] = a
	}
	return is
}

// Map -
func (a ArticleDB) Map(rows *sql.Rows) ([]Article, error) {
	cols, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	dist := []Article{}
	for rows.Next() {
		mapper := make(map[string]interface{})
		di := Article{}
		a.Register(mapper, &di)
		refs := make([]interface{}, len(cols))
		for i, c := range cols {
			refs[i] = mapper[c]
		}
		if err := rows.Scan(refs...); err != nil {
			return nil, err
		}
		dist = append(dist, di)
	}
	return dist, nil
}

// QueryOne Select single record
func (a ArticleDB) QueryOne(sess *sqlabble.Session, s stmt.Statement) (Article, error) {
	query, values := sess.Builder.Build(s)
	rows, err := sess.Query(query, values...)
	if err != nil {
		return Article{}, err
	}
	ms, err := a.Map(rows)
	if err != nil {
		return Article{}, err
	}
	if len(ms) == 0 {
		return Article{}, sqlabble.NewErrRecordNotFound(a.Table.Name)
	}
	if len(ms) > 1 {
		return Article{}, sqlabble.NewErrFoundMultipleRecords(a.Table.Name)
	}
	return ms[0], nil
}

// Count count records
func (a ArticleDB) Count(sess *sqlabble.Session, op stmt.ComparisonOrLogicalOperation) (int64, error) {
	var query string
	var values []interface{}

	fc := sqlabble.Select(sqlabble.Count(sqlabble.Wildcard)).From(a.Table)
	if op != nil {
		query, values = sess.Builder.Build(fc.Where(op))
	} else {
		query, values = sess.Builder.Build(fc)
	}
	rows, err := sess.Query(query, values...)
	if err != nil {
		return 0, err
	}

	var count int64
	for rows.Next() {
		err := rows.Scan(&count)
		if err != nil {
			return 0, err
		}
	}

	return count, nil
}

// Query select some records
func (a ArticleDB) Query(sess *sqlabble.Session, s stmt.Statement) ([]Article, error) {
	query, values := sess.Builder.Build(s)
	rows, err := sess.Query(query, values...)
	if err != nil {
		return []Article{}, err
	}
	ms, err := a.Map(rows)
	if err != nil {
		return []Article{}, err
	}

	return ms, nil
}

// Exec execute a query
func (a ArticleDB) Exec(sess *sqlabble.Session, s stmt.Statement) (sql.Result, error) {
	query, values := sess.Builder.Build(s)
	result, err := sess.Exec(query, values...)
	if err != nil {
		return nil, err
	}
	return result, nil
}
