// Code generated by sqlabble, DO NOT EDIT.
package bar

import (
	"database/sql"
	"strings"

	"github.com/sqlabble/sqlabble"
	"github.com/sqlabble/sqlabble/cmd/sqlabble/fixtures/foo"
	"github.com/sqlabble/sqlabble/stmt"
)

// ArticleDB Article table
type ArticleDB struct {
	Table               stmt.Table
	TableAlias          stmt.TableAlias
	PostIDColumn        stmt.Column
	PostIDColumnAlias   stmt.ColumnAlias
	BodyColumn          stmt.Column
	BodyColumnAlias     stmt.ColumnAlias
	AuthorIDColumn      stmt.Column
	AuthorIDColumnAlias stmt.ColumnAlias
	Author              foo.UserDB
}

// NewArticleDB Create a/an ArticleDB
func NewArticleDB(aliases ...string) ArticleDB {
	alias := strings.Join(aliases, ".")
	if alias == "" {
		alias = "articles"
	}
	return ArticleDB{
		Table:               stmt.NewTable("articles"),
		TableAlias:          stmt.NewTable("articles").As(alias),
		PostIDColumn:        stmt.NewTableAlias(alias).Column("post_id"),
		PostIDColumnAlias:   stmt.NewTableAlias(alias).Column("post_id").As(strings.Join(append(aliases, "PostID"), ".")),
		BodyColumn:          stmt.NewTableAlias(alias).Column("body"),
		BodyColumnAlias:     stmt.NewTableAlias(alias).Column("body").As(strings.Join(append(aliases, "Body"), ".")),
		AuthorIDColumn:      stmt.NewTableAlias(alias).Column("author_id"),
		AuthorIDColumnAlias: stmt.NewTableAlias(alias).Column("author_id").As(strings.Join(append(aliases, "AuthorID"), ".")),
		Author:              foo.NewUserDB(append(aliases, "Author")...),
	}
}

// Register -
func (a ArticleDB) Register(mapper map[string]interface{}, dist *Article, aliases ...string) {
	mapper[strings.Join(append(aliases, "PostID"), ".")] = &dist.PostID
	mapper[strings.Join(append(aliases, "Body"), ".")] = &dist.Body
	mapper[strings.Join(append(aliases, "AuthorID"), ".")] = &dist.AuthorID
	a.Author.Register(mapper, &dist.Author, append(aliases, "Author")...)
}

// Columns -
func (a ArticleDB) Columns() []stmt.Column {
	return []stmt.Column{
		a.PostIDColumn,
		a.BodyColumn,
		a.AuthorIDColumn,
	}
}

// ColumnAliases -
func (a ArticleDB) ColumnAliases() []stmt.ColumnAlias {
	aliases := []stmt.ColumnAlias{
		a.PostIDColumnAlias,
		a.BodyColumnAlias,
		a.AuthorIDColumnAlias,
	}
	aliases = append(aliases, a.Author.ColumnAliases()...)
	return aliases
}

// Selectors -
func (a ArticleDB) Selectors() []stmt.ValOrColOrAliasOrFuncOrSubOrFormula {
	as := a.ColumnAliases()
	is := make([]stmt.ValOrColOrAliasOrFuncOrSubOrFormula, len(as))
	for i, a := range as {
		is[i] = a
	}
	return is
}

// Map -
func (a ArticleDB) Map(rows *sql.Rows) ([]Article, error) {
	cols, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	dist := []Article{}
	for rows.Next() {
		mapper := make(map[string]interface{})
		di := Article{}
		a.Register(mapper, &di)
		refs := make([]interface{}, len(cols))
		for i, c := range cols {
			refs[i] = mapper[c]
		}
		if err := rows.Scan(refs...); err != nil {
			return nil, err
		}
		dist = append(dist, di)
	}
	return dist, nil
}

// QueryOne Select single record
func (a ArticleDB) QueryOne(sess *sqlabble.Session, st stmt.Statement) (Article, error) {
	query, values := sess.Builder.Build(st)
	rows, err := sess.Query(query, values...)
	if err != nil {
		return Article{}, err
	}
	ms, err := a.Map(rows)
	if err != nil {
		return Article{}, err
	}
	if len(ms) == 0 {
		return Article{}, sqlabble.NewErrRecordNotFound(a.Table.Name)
	}
	if len(ms) > 1 {
		return Article{}, sqlabble.NewErrFoundMultipleRecords(a.Table.Name)
	}
	return ms[0], nil
}

// Count count records
func (a ArticleDB) Count(sess *sqlabble.Session, op stmt.ComparisonOrLogicalOperation) (int64, error) {
	var query string
	var values []interface{}

	fc := sqlabble.Select(sqlabble.Count(sqlabble.Wildcard)).From(a.Table)
	if op != nil {
		query, values = sess.Builder.Build(fc.Where(op))
	} else {
		query, values = sess.Builder.Build(fc)
	}
	rows, err := sess.Query(query, values...)
	if err != nil {
		return 0, err
	}

	var count int64
	for rows.Next() {
		err := rows.Scan(&count)
		if err != nil {
			return 0, err
		}
	}

	return count, nil
}

// Query select some records
func (a ArticleDB) Query(sess *sqlabble.Session, st stmt.Statement) ([]Article, error) {
	query, values := sess.Builder.Build(st)
	rows, err := sess.Query(query, values...)
	if err != nil {
		return []Article{}, err
	}
	ms, err := a.Map(rows)
	if err != nil {
		return []Article{}, err
	}

	return ms, nil
}

// Exec execute a query
func (a ArticleDB) Exec(sess *sqlabble.Session, st stmt.Statement) (sql.Result, error) {
	query, values := sess.Builder.Build(st)
	result, err := sess.Exec(query, values...)
	if err != nil {
		return nil, err
	}
	return result, nil
}
