package generator

import (
	"bytes"
	"errors"
	"go/ast"
	"go/format"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"html/template"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/minodisk/caseconv"
	"golang.org/x/tools/imports"
)

const implTmpl = `// Code generated by sqlabble, DO NOT EDIT.
package {{ .Name }}

import (
	"database/sql"
	"strings"

	"github.com/sqlabble/sqlabble"
	"github.com/sqlabble/sqlabble/stmt"
)

{{- range .Tables }}
{{- $receiver := .Reciever }}
{{- $baseType := .GoName }}
{{- $tableName := .DBName }}
{{- $tableType := printf "%sDB" $baseType }}
{{- $mapperType := printf "%sMapper" $baseType }}
// {{ $tableType }} {{ $baseType }} table
type {{ $tableType }} struct{
	Table stmt.Table
	TableAlias stmt.TableAlias
{{- range .Columns }}
	{{- if not .Omit }}
		{{- if .GoRefName }}
			{{ .GoName }} {{ if .GoRefPkgName }}{{ .GoRefPkgName }}.{{ end }}{{ .GoRefName }}DB
		{{- else }}
			{{ .GoName }}Column      stmt.Column
			{{ .GoName }}ColumnAlias stmt.ColumnAlias
		{{- end }}
	{{- end }}
{{- end }}
}

// New{{ $tableType }} Create a/an {{ $tableType }}
func New{{ $tableType }}(aliases ...string) {{ $tableType }} {
	alias := strings.Join(aliases, ".")
	if alias == "" {
		alias = "{{ $tableName }}"
	}
	return {{ $tableType }}{
		Table: stmt.NewTable("{{ .DBName }}"),
		TableAlias: stmt.NewTable("{{ .DBName }}").As(alias),
{{- range .Columns }}
	{{- if not .Omit }}
		{{- if .GoRefName }}
			{{ .GoName }}: {{ if .GoRefPkgName }}{{ .GoRefPkgName }}.{{ end }}New{{ .GoRefName }}DB(append(aliases, "{{ .GoName }}")...),
		{{- else }}
			{{ .GoName }}Column:      stmt.NewTableAlias(alias).Column("{{ .DBName }}"),
			{{ .GoName }}ColumnAlias: stmt.NewTableAlias(alias).Column("{{ .DBName }}").As(strings.Join(append(aliases, "{{ .GoName }}"), ".")),
		{{- end }}
	{{- end }}
{{- end }}
	}
}

// Register -
func ({{ $receiver }} {{ $tableType }}) Register(mapper map[string]interface{}, dist *{{ $baseType }}, aliases ...string) {
{{- range .Columns }}
	{{- if .GoRefName }}
		{{- if not .Omit }}
			{{ $receiver }}.{{ .GoName }}.Register(mapper, &dist.{{ .GoName }}, append(aliases, "{{ .GoName }}")...)
		{{- end }}
	{{- else }}
		mapper[strings.Join(append(aliases, "{{ .GoName }}"), ".")] = &dist.{{ .GoName }}
	{{- end }}
{{- end }}
}

// Columns -
func ({{ $receiver }} {{ $tableType }}) Columns() []stmt.Column {
	return []stmt.Column{
{{- range .Columns }}
	{{- if not .Omit }}
		{{- if not .GoRefName }}
			{{ $receiver }}.{{ .GoName }}Column,
		{{- end }}
	{{- end }}
{{- end }}
	}
}

// ColumnAliases -
func ({{ $receiver }} {{ $tableType }}) ColumnAliases() []stmt.ColumnAlias {
	aliases := []stmt.ColumnAlias{
{{- range .Columns }}
	{{- if not .Omit }}
		{{- if not .GoRefName }}
			{{ $receiver }}.{{ .GoName }}ColumnAlias,
		{{- end }}
	{{- end }}
{{- end }}
	}
{{- range .Columns }}
	{{- if not .Omit }}
		{{- if .GoRefName }}
			aliases = append(aliases, {{ $receiver }}.{{ .GoName }}.ColumnAliases()...)
		{{- end }}
	{{- end }}
{{- end }}
	return aliases
}

// Selectors -
func ({{ $receiver }} {{ $tableType }}) Selectors() []stmt.ValOrColOrAliasOrFuncOrSubOrFormula {
	as := {{ $receiver }}.ColumnAliases()
	is := make([]stmt.ValOrColOrAliasOrFuncOrSubOrFormula, len(as))
	for i, a := range as {
		is[i] = a
	}
	return is
}

// Map -
func ({{ $receiver }} {{ $tableType }}) Map(rows *sql.Rows) ([]{{ $baseType }}, error) {
	cols, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	dist := []{{ $baseType }}{}
	for rows.Next() {
		mapper := make(map[string]interface{})
		di := {{ $baseType }}{}
		{{ $receiver }}.Register(mapper, &di)
		refs := make([]interface{}, len(cols))
		for i, c := range cols {
			refs[i] = mapper[c]
		}
		if err := rows.Scan(refs...); err != nil {
			return nil, err
		}
		dist = append(dist, di)
	}
	return dist, nil
}

// QueryOne Select single record
func ({{ $receiver }} {{ $tableType }}) QueryOne(sess *sqlabble.Session, s stmt.Statement) ({{ $baseType }}, error) {
	query, values := sess.Builder.Build(s)
	rows, err := sess.Query(query, values...)
	if err != nil {
		return {{ $baseType }}{}, err
	}
	ms, err := {{ $receiver }}.Map(rows)
	if err != nil {
		return {{ $baseType }}{}, err
	}
	if len(ms) == 0 {
		return {{ $baseType }}{}, sqlabble.NewErrRecordNotFound({{ $receiver }}.Table.Name)
	}
	if len(ms) > 1 {
		return {{ $baseType }}{}, sqlabble.NewErrFoundMultipleRecords({{ $receiver }}.Table.Name)
	}
	return ms[0], nil
}

// Count count records
func ({{ $receiver }} {{ $tableType }}) Count(sess *sqlabble.Session, op stmt.ComparisonOrLogicalOperation) (int64, error) {
	var query string
	var values []interface{}

	f := sqlabble.Select(sqlabble.Count(sqlabble.Wildcard)).From({{ $receiver }}.Table)
	if op != nil {
		query, values = sess.Builder.Build(f.Where(op))
	} else {
		query, values = sess.Builder.Build(f)
	}
	rows, err := sess.Query(query, values...)
	if err != nil {
		return 0, err
	}

	var count int64
	for rows.Next() {
		err := rows.Scan(&count)
		if err != nil {
			return 0, err
		}
	}

	return count, nil
}

// Query select some records
func ({{ $receiver }} {{ $tableType }}) Query(sess *sqlabble.Session, s stmt.Statement) ([]{{ $baseType }}, error) {
	query, values := sess.Builder.Build(s)
	rows, err := sess.Query(query, values...)
	if err != nil {
		return []{{ $baseType }}{}, err
	}
	ms, err := {{ $receiver }}.Map(rows)
	if err != nil {
		return []{{ $baseType }}{}, err
	}

	return ms, nil
}

// Exec execute a query
func ({{ $receiver }} {{ $tableType }}) Exec(sess *sqlabble.Session, s stmt.Statement) (sql.Result, error) {
	query, values := sess.Builder.Build(s)
	result, err := sess.Exec(query, values...)
	if err != nil {
		return nil, err
	}
	return result, nil
}

{{- end }}
`

var impl *template.Template

func init() {
	var err error
	impl, err = template.New("impl").Parse(implTmpl)
	if err != nil {
		panic(err)
	}
}

func Convert(input []byte, srcPath, destFilename string) ([]byte, error) {
	var scanner *types.Interface
	if !filepath.IsAbs(srcPath) {
		var err error
		srcPath, err = filepath.Abs(srcPath)
		if err != nil {
			return nil, err
		}
	}

	{
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, "database/sql", `package sql
type Scanner interface {
	Scan(src interface{}) error
}
`, 0)
		if err != nil {
			return nil, err
		}
		conf := &types.Config{
			Importer: importer.Default(),
		}
		info := &types.Info{
			Types: map[ast.Expr]types.TypeAndValue{},
			Defs:  map[*ast.Ident]types.Object{},
			Uses:  map[*ast.Ident]types.Object{},
		}
		pkg, err := conf.Check("database/sql", fset, []*ast.File{file}, info)
		if err != nil {
			return nil, err
		}
		scanner = pkg.Scope().Lookup("Scanner").Type().Underlying().(*types.Interface)
	}

	srcDir := filepath.Dir(srcPath)
	srcFilename := filepath.Base(srcPath)

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, srcDir, func(fi os.FileInfo) bool {
		return true
	}, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var (
		fs []*ast.File
		f  *ast.File
	)
	for _, pkg := range pkgs {
		fs = []*ast.File{}
		for fileName, file := range pkg.Files {
			fs = append(fs, file)
			if fileName == srcPath {
				f = file
			}
		}
		if f != nil {
			break
		}
	}
	if f == nil {
		return nil, errors.New("can't find source file")
	}

	conf := &types.Config{
		Importer: importer.For("source", nil),
	}
	info := &types.Info{
		Defs: map[*ast.Ident]types.Object{},
		Uses: map[*ast.Ident]types.Object{},
	}
	if _, err := conf.Check("github.com/sqlabble/sqlabble/cmd/sqlabble/foo/bar/baz/"+srcFilename, fset, fs, info); err != nil {
		return nil, err
	}

	// fmt.Println("==================")
	// fmt.Println(p)
	// fmt.Println("DEFS=====")
	// for k, v := range info.Defs {
	// 	fmt.Printf("%s: %+v\n", k, v)
	// }
	// fmt.Println("USES=====")
	// for k, v := range info.Uses {
	// 	fmt.Printf("%s: %+v\n", k, v)
	// }

	if ok := ast.FileExports(f); !ok {
		return nil, errors.New("nothing to export")
	}

	pkg := ParsePackage(fset, info, f, scanner)
	if len(pkg.Tables) == 0 {
		return nil, errors.New("no table found in package")
	}

	var buf bytes.Buffer
	if err := impl.Execute(&buf, pkg); err != nil {
		return nil, err
	}

	code := buf.Bytes()
	code, err = imports.Process(destFilename, code, nil)
	if err != nil {
		return nil, err
	}
	code, err = format.Source(code)
	if err != nil {
		return nil, err
	}
	return code, nil
}

type Package struct {
	Name   string
	Tables []Table
}

type Table struct {
	GoName   string
	DBName   string
	Columns  []Column
	Reciever string
	ident    *ast.Ident
}

type Column struct {
	Omit         bool
	GoName       string
	GoRefPkgName string
	GoRefName    string
	DBName       string
}

type Comment struct {
	Position  token.Position
	TableName string
}

type Comments []Comment

func (cs Comments) Find(from, to int) (Comment, bool) {
	for _, c := range cs {
		if from <= c.Position.Line && c.Position.Line <= to {
			return c, true
		}
	}
	return Comment{}, false
}

func ParsePackage(fset *token.FileSet, info *types.Info, file *ast.File, scanner *types.Interface) Package {
	comments := Comments{}
	for _, comment := range file.Comments {
		for _, cm := range comment.List {
			c := cm.Text
			c = strings.TrimSpace(strings.TrimPrefix(c, "//"))
			if len(c) == 0 || c[0] != '+' {
				continue
			}
			c = c[1:]
			if n, ok := ParseDBTag(c); ok {
				comments = append(comments, Comment{
					Position:  fset.Position(cm.Pos()),
					TableName: n,
				})
			}
		}
	}

	p := Package{Name: file.Name.Name}
	ast.Inspect(file, func(node ast.Node) bool {
		switch s := node.(type) {
		case *ast.TypeSpec:
			start := fset.Position(node.Pos()).Line
			end := fset.Position(node.End()).Line
			c, ok := comments.Find(start-1, end)
			if !ok {
				return false
			}

			t := ParseTable(fset, info, s, scanner)
			if c.TableName != "" {
				t.DBName = c.TableName
			}
			p.Tables = append(p.Tables, t)

			return false
		}
		return true
	})

	return p
}

func ParseTable(fset *token.FileSet, info *types.Info, typ *ast.TypeSpec, scanner *types.Interface) Table {
	var (
		table Table
		found bool
	)
	ast.Inspect(typ, func(node ast.Node) bool {
		if found {
			return false
		}

		switch s := node.(type) {
		case *ast.Ident:
			table.ident = s
		case *ast.StructType:
			if typ.Name.Name == "" {
				return true
			}
			table.GoName = typ.Name.Name
			table.Reciever = string(strings.ToLower(typ.Name.Name)[0])
			table.DBName = caseconv.LowerSnakeCase(typ.Name.Name)
			for _, field := range s.Fields.List {
				column := ParseColumn(fset, info, field, scanner)
				if column != nil {
					table.Columns = append(table.Columns, *column)
				}
			}

			found = true
			return false
		}

		return true
	})

	return table
}

func ParseColumn(fset *token.FileSet, info *types.Info, field *ast.Field, scanner *types.Interface) *Column {
	var (
		column Column
		ident  *ast.Ident
		tag    *ast.BasicLit
	)

	ast.Inspect(field, func(node ast.Node) bool {
		if node == nil {
			return false
		}
		switch t := node.(type) {
		case *ast.Ident: // find field type
			if ident == nil {
				ident = t
				obj := info.Defs[ident]
				typ := obj.Type()
				if types.Implements(types.NewPointer(typ).Underlying(), scanner) {
					return false
				}
				myPkg := obj.Pkg()
				if myTypeNamed, ok := typ.(*types.Named); ok {
					refPkg := myTypeNamed.Obj().Pkg()
					if myPkg == refPkg {
						column.GoRefName = myTypeNamed.Obj().Name()
					} else {
						column.GoRefPkgName = refPkg.Name()
						column.GoRefName = myTypeNamed.Obj().Name()
					}
				}
			}
		case *ast.BasicLit: // find tag
			if t.Kind == token.STRING {
				tag = t
			}
		}
		return true
	})

	column.GoName = ident.Name
	if tag != nil {
		if name, ok := ParseDBTag(strings.Trim(tag.Value, "`")); ok {
			if name == "-" {
				column.Omit = true
			} else {
				column.DBName = name
			}
		}
	}

	return &column
}

func ParseDBTag(s string) (string, bool) {
	return reflect.StructTag(s).Lookup("db")
}
